fn_args_layout = "Compressed"
format_strings = true
max_width = 100
normalize_comments = true
reorder_imports = true
spaces_around_ranges = true
unstable_features = true
use_small_heuristics = "Max"
use_try_shorthand = true
